# Site settings
title: Claíomh Solais
header-img: img/home-bg.jpg
email: solais.info@gmail.com
description: "女性弾き語りDuo「Claíomh Solais～クラウソラス～」のホームページです。"
baseurl: "https://claiomhsolais.jp"
url: "https://claiomhsolais.jp"
twitter_username: ibukiyui0614
twitter_name: Yui
twitter2_username: Kadojundesu
twitter2_name: Jun
#github_username:  claionhsolais
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
