# Site settings
title: Claíomh Solais
header-img: img/home-bg.jpg
email: solais.info@gmail.com
description: "女性弾き語りDuo「Claíomh Solais～クラウソラス～」のホームページです。"
baseurl: ""
url: "https://claiomhsolais.jp"
blog: "http://ameblo.jp/claiomhsolais/"
twitter_username: ibukiyui0614
twitter_name: Yui
twitter_fullname: Yui Ibuki
twitter_picture: img/yui.jpg
twitter2_username: Kadojundesu
twitter2_name: Jun
twitter2_fullname: Jun Kadotani
twitter2_picture: img/jun.jpg
#github_username:  claionhsolais
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

collections:
  events:
    output: true
    permalink: /event/:path/

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
